version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "khoren93"
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "khoren93"
  # - package-ecosystem: "pub"
  #   directory: "/example"
  #   schedule:
  #     interval: "monthly"
  #   reviewers:
  #     - "khoren93"
  # - package-ecosystem: "pub"
  #   directory: "/zxscanner"
  #   schedule:
  #     interval: "monthly"
  #   reviewers:
  #     - "khoren93"
